### ISSUE TITLE
Chapter1 中README 笔误

### ISSUE THREAD

**Issue by PetalsOnaWet** [tank0317/unit-test-demo#4]
>`expect([1,2,3].indexOf(4)).to.equal(-1)`<br>
上面这句断言的意思是，调用`[1,2,3].indexOf(4)`，结果应该等于 -1。所谓"断言"，就是判断源码的实际执行结果与预期结果是否一致，如果不一致就抛出一个错误。

段落中的这句话`结果应该等于 2`是否为一个笔误，按照我的理解，此处应为` 结果应该等于-1`

**Comment by tank0317** [comment]
对，是笔误。谢谢反馈
